server:
  port: 8090
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: bb7e813745579c8cc51b
            client-secret: e4f0f88eca30ab079f8fa3d975b378582c26a27e
          keycloak:
            client-id: data-gateway-application
            client-secret: EGYEDrFTXAkLU1tcc0Me2Cjk8BjkQEKY
            authorization-grant-type: authorization_code
            scope:
              - openid
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:9000/realms/master
            user-name-attribute: preferred_username