server:
  port: 8090
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: data-gateway-application
            client-secret: vNF70uu3c0wpNV3GKrsuE1x7QiV6h0DC
            authorization-grant-type: authorization_code
            scope:
              - openid
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:9000/realms/cloud-gateway
            user-name-attribute: preferred_username