server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/realms/cloud-gateway/protocol/openid-connect/certs
          token-uri: http://localhost:9000/realms/cloud-gateway/protocol/openid-connect/token